# 起動済のtmux sessionがあればattachする
# 残っていなければtmuxを起動する
shell:
  program: /bin/zsh
  args:
    - -l
      # - -c
      # - 'tmux attach || tmux'

# Colors (iTerm 2 default theme)
colors:
  # Default colors
  primary:
    background: '#101421'
    foreground: '#fffbf6'

  # Normal colors
  normal:
    black:   '#2e2e2e'
    red:     '#eb4129'
    green:   '#abe047'
    yellow:  '#f6c744'
    blue:    '#47a0f3'
    magenta: '#7b5cb0'
    cyan:    '#64dbed'
    white:   '#e5e9f0'

  # Bright colors
  bright:
    black:   '#565656'
    red:     '#ec5357'
    green:   '#c0e17d'
    yellow:  '#f9da6a'
    blue:    '#49a4f8'
    magenta: '#a47de9'
    cyan:    '#99faf2'
    white:   '#ffffff'

# ウィンドウ設定
window:
  # タイトルバー非表示
  # decorations: "transparent"
  # decorations: "none"
  # decorations: "buttonless"

  # 初期ウィンドウサイズ
  dimensions:
    columns: 100
    lines: 35

  # 余白設定
  padding:
    x: 8
    y: 8

  # 透過設定（これが無いとMissionControlが不安定になる）
  background_opacity: 0.999

# スクロール設定
scrolling:
  # consoleのlogを10000行まで保持
  history: 10000

  # スクロール量は3行
  multiplier: 3

# フォント設定
font:
  normal:
    family: 'HackGen Console NF'
    style: Regular

  bold:
    family: 'HackGen Console NF'
    style: Bold

  size: 13.0

  offset:
    y: 1

