# 起動済のtmux sessionがあればattachする
# 残っていなければtmuxを起動する
shell:
  program: /bin/zsh
  args:
    - -l
      # - -c
      # - 'tmux attach || tmux'

# Colors (One Dark)
# https://github.com/alacritty/alacritty-theme
colors:
  # Default colors
  primary:
    background: '0x1e2127'
    foreground: '0xabb2bf'

  # Normal colors
  normal:
    black:   '0x1e2127'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xabb2bf'

  # Bright colors
  bright:
    black:   '0x5c6370'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xffffff'

# ウィンドウ設定
window:
  # タイトルバー非表示
  # decorations: "transparent"
  # decorations: "none"
  # decorations: "buttonless"

  # 初期ウィンドウサイズ
  dimensions:
    columns: 100
    lines: 35

  # 余白設定
  padding:
    x: 8
    y: 8

  # 透過設定（これが無いとMissionControlが不安定になる）
  background_opacity: 0.999

# スクロール設定
scrolling:
  # consoleのlogを10000行まで保持
  history: 10000

  # スクロール量は3行
  multiplier: 3

# フォント設定
font:
  normal:
    family: 'HackGen Console NF'
    style: Regular

  bold:
    family: 'HackGen Console NF'
    style: Bold

  size: 13.0

  offset:
    y: 1

