onboarding = false

[theme]
name = "terminal"

[keys]
prefix = "ctrl+j"

[ui]
mouse_capture = false
pane_gaps = false
hide_tab_bar_when_single_tab = true
pane_scrollbars=false

[experimental]
pane_history = false

